### ISSUE TITLE
[BUG]Possible issue with VPN users on Linux

### ISSUE THREAD

**Issue by Velenthis** [SoMuchForSubtlety/f1viewer#108]
My region doesn't have F1TV Pro, so I have to use a VPN to start the stream and then disconnect from it for better performance. In Windows it worked perfectly, but on Linux(Mint) the stream doesn't keep going if the network changes.

This may be an issue on Linux's mpv or ProtonVPN tho.

**Comment by PeteSeta** [comment]
I’m on Windows 10 64bit and I have to keep my VPN on the whole time or the stream will buffer indefinitely after disconnecting. It’s not a Linux issue

**Comment by eXhumer1** [comment]
Have you tried to check if it actually is f1viewer that is causing the issue and not F1TV? Because, from my testing, I noticed that F1TV refuses to send back the master playlist after you change IP address.

![image](https://user-images.githubusercontent.com/73384968/101237889-8689b500-3699-11eb-8e35-22c79b0cc133.png)
