### ISSUE TITLE
Driver stream now starts on audio channel 2/7 (english commentary)

### ISSUE THREAD

**Issue by kross123** [SoMuchForSubtlety/f1viewer#194]
Version: 2.4.0 - Windows
Player: mpv

Since my upgrade to 2.4.0 when I start a driver stream it starts on audio channel 2/7 (english commentary). It used to open automatically with the onboard/team radio.

Changing to 1/7 audio causes it to cache the stream completely from the start of the broadcast. Skipping ahead is not possible, but this is not related I think.

Please open the driver streams with the onboard audio by default as changing streams won't work. Most will have the world stream already open with the english commentary.

Again thanks for this great project!!

**Comment by warbi** [comment]
Spotted this too. I downgraded to 2.3.0 and the problem persists so I'm thinking this could be an F1TV issue rather than F1Viewer.

**Comment by SoMuchForSubtlety** [comment]
What's your language preference set to in your config? You can open it by running `f1viewer -config`. Set `preferred_language` to `fx` if you want no commentary.

**Comment by warbi** [comment]
Thanks @SoMuchForSubtlety, changing `preferred_language` in config.json to `teamradio` launches World Feed in `7/7 Eng` and driver streams in `1/7 Teamradio` which is fine for me (though maybe not for those wanting other languages on the world feed). 

Perhaps rather than introducing separate settings you could simply launch driver streams with `Teamradio` audio by default and ignore the user preferences? I can't imagine anyone would want anything else... personally I use the World Feed audio for commentary.

As @kross123 mentioned I was also getting the livestream rewind issues when changing driver audio from `Eng` to `Teamradio`.  I'd expect launching directly with `Teamradio` will fix that but this is something we'll only be able to test at the next live session.

Thanks for your work on this, it's a really great tool you've put together 👍

**Comment by kross123** [comment]
I looked at the settings.json. My lanuage was set to "eng", and I changed it to "team" and it worked the same way @SoMuchForSubtlety  described with "teamradio". So I have a fix now. When I changed it, I didn't see the update in this post yet and was searching for valid preferred_language settings, but could not find it. Maybe something to add to the readme or wiki.
