### ISSUE TITLE
ERROR: got status 400 Bad Request with body

### ISSUE THREAD

**Issue by Shako131** [SoMuchForSubtlety/f1viewer#42]
Hello, I can't play any Formula 1 steams. https://prnt.sc/rdfkwn

**Comment by SoMuchForSubtlety** [comment]
can you please provide logs from `%appdata%\f1viewer\logs`

**Comment by Shako131** [comment]
[2020-03-08.log](https://github.com/SoMuchForSubtlety/f1viewer/files/4303781/2020-03-08.log)

**Comment by SoMuchForSubtlety** [comment]
Thank you, I'll investigate.

**Comment by SoMuchForSubtlety** [comment]
Do you have an F1TV pro or access subscription?

**Comment by Shako131** [comment]
Not

**Comment by Shako131** [comment]
I have only account, not subscription.

**Comment by SoMuchForSubtlety** [comment]
Does it happen with everything you try to play?

**Comment by Shako131** [comment]
Yes

**Comment by SoMuchForSubtlety** [comment]
The error is likely because your account does not have a pro or access subscription.  I can't do anything about that at this time.

**Comment by Shako131** [comment]
If I had a premium account, why would I use your app? That I don't have, I used it.

**Comment by ambiguous48** [comment]
First, thanks for this App.

I seem to have the same issue as OP, even though I have a Pro account. When I try to play most files I get the following error.
`2020/07/03 09:52:40 [ERROR] got status 400 Bad Request with body:
{"skylark_error_code": null, "form_validation_errors": null, "error": "The content must have a schedule that matches the current schedule filters"}`

I've only found one file that plays normally. All other files produce this same error.

A file that _doesn't_ work: Full Race Weekends > 2019 Formula 1 WC > Australia > Race > Main Feed > Play with MPV
The file that works: Documentary > Kings of Monace > Play with MPV


Also, everything inside "Collections" shows "no content" when I expand the subtrees. My account works, when I log into f1tv.com I can watch all the race replays just fine. 

I'm not sure what the issue is. The log file only produces the error I pasted above. If there is any more info I can provide let me know.  Thanks again.

**Comment by jfoster** [comment]
I'm also encountering the same error message while attempting to view live sessions, 2019 Full Race Weekends are working, however 2020 pre-season testing and 2020 Austrian GP are producing the same error message.

I reside within the UK but have F1 TV Pro purchased through the play store using a Dutch VPN, same errors produced with and without the VPN active.
