### ISSUE TITLE
Able to use VLC?

### ISSUE THREAD

**Issue by MrCubie** [SoMuchForSubtlety/f1viewer#80]
Is it possible to use VLC instead of MPV?
MPV is missing some features I'm familiar with in VLC.

**Comment by SoMuchForSubtlety** [comment]
You can add a custom playback option as described [here](https://github.com/SoMuchForSubtlety/f1viewer/issues/50#issuecomment-653163183). You can read more about custom command [in the readme](https://github.com/SoMuchForSubtlety/f1viewer#Custom-commands)

I don't include VLC by default since it does not support multi-channel HLS streams properly, but some users have reported it working properly for them.

**Comment by ikt** [comment]
Does anyone have what the custom command would be to open in VLC? ngl mpv works ok for me but it would be nice to have it in the example.

**Comment by MrCubie** [comment]
> You can add a custom playback option as described [here](https://github.com/SoMuchForSubtlety/f1viewer/issues/50#issuecomment-653163183). You can read more about custom command [in the readme](https://github.com/SoMuchForSubtlety/f1viewer#Custom-commands)
> 
> I don't include VLC by default since it does not support multi-channel HLS streams properly, but some users have reported it working properly for them.

That worked thanks, Love the program! Great job

**Comment by SoMuchForSubtlety** [comment]
@ikt in your config replace `"custom_playback_options": [],` with 
```
"custom_playback_options": [
	{
		"title": "Play with VLC",
		"command": ["vlc", "$url"]
	}
],
```
